### ISSUE TITLE
Schema Elettrico ed ESP8266

### ISSUE THREAD

**Issue by wes1993** [lucasimons/midea-clivet-aquaswan-modbus#1]
Ciao,
Ho visto il tuo progetto, posso chiederti come lo hai interfacciato con internet? Il mio non ha Wi-Fi ma solo display…

grazie mille 
Stefano

**Comment by lucasimons** [comment]
Puoi usare un classico convertitore modbus wifi il più economico è ew 11 sennò tramite esphome

**Comment by wes1993** [comment]
Grazie mille per la risposta @lucasimons 

ma se volessi usare esphome, come dovrei collegare un esp8266? Il codice poi, andrebbe bene il tuo?

**Comment by lucasimons** [comment]
Questo è lo schema che devi seguire se usi esphome con un convertitore rs485

![image](https://user-images.githubusercontent.com/67467751/220086214-bf019c55-b85c-4339-8fb5-105b5bc88089.png)
 
Il codice è diverso perchè ho sfruttato l'integrazione natica di HA con modbus però i registri sono gli stessi va leggermente adattato per usarlo con Esphome

**Comment by wes1993** [comment]
Grazie mille per la risposta!! :)

ti aggiorno appena faccio qualche prova :)

**Comment by wes1993** [comment]
Ciao,
alla fine ho preso l'EW11, ho i seguenti settaggi per la porta seriale, puoi confermarmi che sono corretti o se devo modificare qualche cosa?

![image](https://user-images.githubusercontent.com/52070589/227712939-471aa2ac-a796-4282-be65-1e8f3d6ac3ad.png)


![image](https://user-images.githubusercontent.com/52070589/227712950-a683fb61-7fd5-4306-ab8a-55f14c7552d5.png)


Dalla pagina status vedo tutto a 0 è nromale?
![image](https://user-images.githubusercontent.com/52070589/227712986-51ed99c0-f096-4012-8110-cd1ad94f5dee.png)

Grazie mille
Stefano

**Comment by lucasimons** [comment]
> Ciao, alla fine ho preso l'EW11, ho i seguenti settaggi per la porta seriale, puoi confermarmi che sono corretti o se devo modificare qualche cosa?
> 
> ![image](https://user-images.githubusercontent.com/52070589/227712939-471aa2ac-a796-4282-be65-1e8f3d6ac3ad.png)
> 
> ![image](https://user-images.githubusercontent.com/52070589/227712950-a683fb61-7fd5-4306-ab8a-55f14c7552d5.png)
> 
> Dalla pagina status vedo tutto a 0 è nromale? ![image](https://user-images.githubusercontent.com/52070589/227712986-51ed99c0-f096-4012-8110-cd1ad94f5dee.png)
> 
> Grazie mille Stefano

si sono giusti hai provato ad invertire A e B, hai attivato tramite la procedura di tasti? 
![image](https://github.com/lucasimons/midea-clivet-aquaswan-modbus/assets/67467751/252e37de-47b4-434c-b54c-8e63d066d01d)
